services:
  springboot:
    image: openjdk:20-jdk-slim
    container_name: talkwave-springboot
    expose:
      - "8080"
    working_dir: /app
    entrypoint: ["java", "-jar", "talkwave.jar"]
    environment:
      TZ: Asia/Seoul
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    networks:
      - app
    restart: always

networks:
  app:
    name: app
    driver: bridge
